<?php

namespace FBA\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MuestraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuestraRepository extends EntityRepository
{
}
