<?php

namespace FBA\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VigenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VigenciaRepository extends EntityRepository
{
}
